config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :comments
  get '/comments' => 'entries#new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  post 'entry/new' => 'entries#new'
  get 'entry/new' => 'entries#new'
  get 'homepage' => 'visitors#index'
  post 'pages/entry/new' => 'entries#new'
  resources :users
  root 'visitors#index'
  post 'login' => 'sessions#create'
  post 'entries/entry/new' => 'entries#new'
  get 'comment' => 'comments#new'
  get 'entries/entry/new' => 'entries#new'
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @entry= Entry.new
    @entries = Entry.where(["date <= ?" , Date.today])
    if params[:search]
      @entries = Entry.search(params[:search]).order('created_at DESC')
    else
      @entries = Entry.all.paginate(:page => params[:page], :per_page => 10)
    end
  end
    @user= User.new
    @users = User.all
    @comment = Comment.new
    @comments = Comment.all
  end

app/views/visitors/index.html.erb
<!-- Page Content -->
  <div class="container">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 style="border-bottom: 2px black solid; padding-bottom: 60px;">
              <img src="/images/logo.png" />
            </h1>

            <!-- First Blog Post -->

              <% for entry in @entries %>
              <div class="panel panel-default">
                <div class="panel panel-heading"><h2>Tytuł postu:
                  <span style="color: #956626 ;"><%= entry.title %></span>
                </h2></div>
              <div class="panel panel-body">
                <a class="pull-left">
                  <img class="media-object" src=<%=entry.user.avatar(:img) %> alt="">
                </a>
            <p>
               dodany przez <span class="h3" style="color: #4cae4c;"><%= entry.nick %></span>
            </p>
            <h5>Kategoria: <span class="h3" style="color: #1b6d85;"><%= entry.category %></span></h5>
            <p><span class="glyphicon glyphicon-time"></span> Zamieszczony <%= entry.created_at.strftime("%d %b. %Y %H:%M") %></p>
            <hr>
                <div class="form-group">
                  <img class="img-responsive" src=<%=entry.image(:normal)%>
                </div>
            <hr>
            <p style="color: #31b0d5">Treść postu: <p style="word-break: break-all;"><%= entry.contents %></p></p>
              <hr>
            <a><%= link_to ('Więcej <span class="glyphicon glyphicon-chevron-right"></span>').html_safe, entry_path(entry.id), :class => "btn btn-primary" %></a>


              </div>
              </div>
              </div>
              <% end %>
            <!-- Pager -->
          <ul class="pager">
            <% if @entries.count > 10 %>
                <div class="center">
                  <%= will_paginate @entries, renderer: BootstrapPagination::Rails %>
                </div>
            <%end%>
            </ul>

        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Blog Search Well -->
            <div class="well">
                <h4>Blog wyszukiwanie</h4>
                <div class="input-group">
                      <%= form_tag(entries_path, :method => "get", id: "search-form") do %>
                          <%= text_field_tag :search, params[:search], placeholder: "Szukaj Postów" %>
                          <%= submit_tag "Szukaj" %>
                      <% end %>
                </div>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Kategorie postów</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                          <li><%= link_to "Muzyka ", entries_path(:category=>"Muzyka")%>[<%= Entry.where(category: "Muzyka").count%>]</li>
                          <li><%= link_to "Podróże ", entries_path(:category=>"Podróże")%>[<%= Entry.where(category: "Podróże").count%>]</li>
                          <li><%= link_to "Styl ", entries_path(:category=>"Styl")%>[<%= Entry.where(category: "Styl").count%>]</li>
                          <li><%= link_to "Żywność ", entries_path(:category=>"Żywność")%>[<%= Entry.where(category: "Żywność").count%>]</li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                          <li><%= link_to "Film ", entries_path(:category=>"Film")%>[<%= Entry.where(category: "Film").count%>]</li>
                          <li><%= link_to "Technologia ", entries_path(:category=>"Technologia")%>[<%= Entry.where(category: "Technologia").count%>]</li>
                          <li><%= link_to "Hobby ", entries_path(:category=>"Hobby")%>[<%= Entry.where(category: "Hobby").count%>]</li>
                          <li><%= link_to "Inne ", entries_path(:category=>"Inne")%>[<%= Entry.where(category: "Inne").count%>]</li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>

            <!-- Side Widget Well -->
            <div class="well">
                <h4>Losowy content</h4>
              <% if entry_all.count <= 0 %>
                  <%= print 'proszę się zarejestrować' %>
              <%else%>
              <p class="pull-left">
                    <img class="media-object" src="<%=random_avatar.avatar(:img)%>" alt="">
                    </p>
                 <p>Nick: <span style="color: #4cae4c;"><%= random_items.nick %></span></p>
                    <p>Tytuł: <span style="color: #956626 ;"><%= random_items.title %></span></p>
                    <p>Kategoria: <span style="color: #1b6d85;"><%= random_items.category %></span></p>
                      <div style="word-break: break-all;"><p style="color: #31b0d5">Treść postu:</p> <%= random_items.contents %></div>
                    <p><small><%= random_items.created_at.strftime("%d %b. %Y %H:%M") %></small></p>
                <% if random_items.youtube_url %>
                    <%= youtube_embed random_items.youtube_url %>
                  <%end%>
                <%end%>
            </div>

        </div>

    </div>
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-xs-12">
                <p>Copyright &copy; K.O Website 2016</p>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->