config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :comments
  get '/comments' => 'entries#new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  post 'entry/new' => 'entries#new'
  get 'entry/new' => 'entries#new'
  get 'homepage' => 'visitors#index'
  post 'pages/entry/new' => 'entries#new'
  resources :users
  root 'visitors#index'
  post 'login' => 'sessions#create'
  post 'entries/entry/new' => 'entries#new'
  get 'comment' => 'comments#new'
  get 'entries/entry/new' => 'entries#new'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :contents, presence: true
  validates :category, presence: true
  validates :image, presence: true
  has_many :comments
  belongs_to :user
  has_attached_file :image, styles: { normal: "900x300" },
  :storage => :dropbox,
      :dropbox_credentials => "#{Rails.root}/config/dropbox_config.yml",
      :dropbox_options => {
          :path => proc { |style| "#{style}/#{id}_#{image.original_filename}"},
          :unique_filename => true},
          :dropbox_visibility => 'public'
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  def self.search(query)
    where("title like ?", "%#{query}%")
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entry = Entry.offset(rand(Entry.count)).first
    if params[:search]
      @entries = Entry.search(params[:search]).order("created_at DESC")
      else
    if params[:category]
      @entries = Entry.where(:category => params[:category])
      flash[:notice] = "<b>#{@entries.count}</b> postów w tej kategorii".html_safe
    else
      @entries = Entry.all.order("created_at DESC") && Entry.where(["date <= ?" , Date.today])
    end
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params["id"])
  end
  # GET /entries/new
  def new
    @entry = Entry.new
  end
  def category
    @entry = Entry.find(params["category"])
  end
  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params["id"])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def date
    time = Time.new

    values = time.to_a
    puts Time.utc(*values)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:id, :title, :date, :contents, :image, :youtube_url, :youtube_embed, :nick, :category, :user_id, :image_file_name)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    raw %Q{<iframe title="YouTube video player" width="320" height="240" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end
end

app/views/entries/_form.html.erb
<%= simple_form_for@entry,html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.input :title, label:'Tytuł postu' %>
    <%=  f.hidden_field :nick, value: current_user.nick %>
    <%= f.input_field :date,as: :date, start_month: Date.today.month,
                end_month: Date.today.month + 12, start_year: Date.today.year, end_year: Date.today.year+1,
                order: [:day, :month, :year]%>
    <p style="padding-top: 10px;"><%= f.label :category,label:'Kategoria Postu [zaznacz jedną]'%></p>
    <%= f.input_field :category, as: :radio_buttons, collection: ["Muzyka","Podróże","Styl","Żywność","Film","Technologia","Hobby","Inne"],:checked => "Inne"%>
    <%= f.input :contents, label: 'Treść postu',:default => "First Line \n Second Line \n Third Line" %>
    <%= f.label :youtube_url,label:'Link Youtuba [wymagany]' %>
    <%= f.input_field :youtube_url, value:'https://' , hint: 'np.https://www.youtube.com/watch?v=[film_unique_id]' %>
    <%= f.input :image, label:'Zdjęcie' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Dodaj Post"%>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Edycja Postu</h1>

<%= render 'form' %>

<%= link_to 'Pokaż', @entry %> |
<%= link_to 'Wstecz', entries_path %>

app/views/entries/index.html.erb
<h1>Wyszukane:</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.date %></td>
        <td><%= entry.contents %></td>
        <td><%= link_to 'Pokaż', entry %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/entries/new.html.erb
<h1>Dodaj post</h1>

<%= render 'form' %>

<div class="form-actions"><%= button_to 'Wstecz', homepage_path, class:'btn btn-default' %></div>

app/views/entries/show.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-md-8">

      <!-- Blog Post -->
      <div class="panel panel-default" style="margin-top: 20px">
        <div class="panel panel-heading"><h2>Tytuł postu:
          <span style="color: #956626 ;"><%= @entry.title %></span>
        </h2></div>
        <div class="panel panel-body">
          <a class="pull-left">
            <img class="media-object" src=<%=@entry.user.avatar(:img) %> alt="">
          </a>
          <p>
            dodany przez <span class="h3" style="color: #4cae4c;"><%= @entry.nick %></span>
          </p>
          <h5>Kategoria: <span class="h3" style="color: #1b6d85;"><%= @entry.category %></span></h5>
          <p><span class="glyphicon glyphicon-time"></span> Zamieszczony <%= @entry.created_at.strftime("%d %b. %Y %H:%M") %></p>
          <hr>
          <div class="row">
            <div class="col-xs-6">
              <div class="form-group">
                <img class="img-responsive" src=<%=@entry.image(:normal)%>>
              </div>
            </div>
            <div class="col-xs-6">
              <div class="form-group">
                  <% if @entry.youtube_url %>
                      <%= youtube_embed @entry.youtube_url %>
                  <%end%>
              </div>
            </div>
          </div>
          <hr>
          <p style="color: #31b0d5">Treść postu: <p style="word-break: break-all;"><%= @entry.contents %></p></p>
          <hr>
      </div>
      </div>
      <hr>
          <!-- Preview Image -->

      <!-- Blog Comments -->


      <hr>

      <!-- Posted Comments -->

      <!-- Comment -->
      <%= simple_form_for(Comment.new) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.hidden_field :nick, value: @entry.nick %>
            <%= f.input :contents, label:"Komentuj post" %>
            <%= f.hidden_field :entry_id, value: @entry.id %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Dodaj komentarz", style:'padding: 10px; margin-bottom: 10px;' %>
          </div>
      <% end %>
      <!-- Comment -->

        <% for comment in @entry.comments %>
        <div class="panel panel-default">
          <div class="panel panel-body">
          <h4 class="media-heading"><%= comment.nick %>
            <small><%= comment.created_at.strftime("%d %b. %Y %H:%M") %></small>
          </h4>
          <%= comment.contents %>
        </div>
        </div>
        <%end%>
      </div>


    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Blog Search Well -->
      <div class="well" style="margin-top: 20px">
          <h4>Losowy content</h4>
        <% if entry_all.count <= 0 %>
            <%= flash.notice 'proszę się zarejestrować' %>
            <%else%>
          <p class="pull-left">
            <img class="media-object" src="<%=random_avatar.avatar(:img)%>" alt="">
          </p>
          <p>Nick: <span style="color: #4cae4c;"><%= random_items.nick %></span></p>
          <p>Tytuł: <span style="color: #956626 ;"><%= random_items.title %></span></p>
          <p>Kategoria: <span style="color: #1b6d85;"><%= random_items.category %></span></p>
          <div style="word-break: break-all;"><p style="color: #31b0d5">Treść postu:</p> <%= random_items.contents %></div>
          <p><small><%= random_items.created_at.strftime("%d %b. %Y %H:%M") %></small></p>
            <%end%>
          <% if @entry.youtube_url %>
              <%= youtube_embed random_items.youtube_url %>
          <%end%>
      </div>

      <!-- Blog Categories Well -->
      <div class="well">
        <h4>Blog Categories</h4>
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled">
              <li><%= link_to "Muzyka ", entries_path(:category=>"Muzyka")%>[<%= Entry.where(category: "Muzyka").count%>]</li>
              <li><%= link_to "Podróże ", entries_path(:category=>"Podróże")%>[<%= Entry.where(category: "Podróże").count%>]</li>
              <li><%= link_to "Styl ", entries_path(:category=>"Styl")%>[<%= Entry.where(category: "Styl").count%>]</li>
              <li><%= link_to "Żywność ", entries_path(:category=>"Żywność")%>[<%= Entry.where(category: "Żywność").count%>]</li>
            </ul>
          </div>
          <!-- /.col-lg-6 -->
          <div class="col-lg-6">
            <ul class="list-unstyled">
              <li><%= link_to "Film ", entries_path(:category=>"Film")%>[<%= Entry.where(category: "Film").count%>]</li>
              <li><%= link_to "Technologia ", entries_path(:category=>"Technologia")%>[<%= Entry.where(category: "Technologia").count%>]</li>
              <li><%= link_to "Hobby ", entries_path(:category=>"Hobby")%>[<%= Entry.where(category: "Hobby").count%>]</li>
              <li><%= link_to "Inne ", entries_path(:category=>"Inne")%>[<%= Entry.where(category: "Inne").count%>]</li>
            </ul>
          </div>
        </div>
        <!-- /.row -->
      </div>

      <!-- Side Widget Well -->
      <div class="well">
        <h4>Random Post Content</h4>
        <p style="word-break: break-all;"> <%=random_items.contents %></p>
      </div>
    </div>

  </div>
  <!-- /.row -->

  <hr>

  <!-- Footer -->
</div>